name: webview_flutter_android
description: A Flutter plugin that provides a WebView widget on Android.
repository: https://github.com/wenzhiming/flutter-plugins/tree/dev/packages/webview_flutter/webview_flutter_android
issue_tracker: https://github.com/wenzhiming/flutter-plugins/issues
version: 2.8.9


environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin

dependencies:
  flutter:
    sdk: flutter
#  webview_pro_platform_interface: ^1.9.0
  webview_flutter_platform_interface:
    git:
      url: https://github.com/sribuu/flutter-plugins.git
      ref: dev-3.0.4
      path: packages/webview_flutter/webview_flutter_platform_interface

dev_dependencies:
  build_runner: ^2.1.4
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  pedantic: ^1.10.0
  pigeon: ^3.0.3
