name: webview_flutter
description: A Flutter plugin that provides a WebView widget who Support photo upload/take camera and Geolocation.
repository: https://github.com/wenzhiming/flutter-plugins/tree/dev/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/wenzhiming/flutter-plugins/issues
version: 3.0.4


environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
#  webview_pro_android: ^2.8.9
  webview_flutter_android:
    git:
      url: https://github.com/sribuu/flutter-plugins.git
      ref: dev-3.0.4
      path: packages/webview_flutter/webview_flutter/webview_flutter_android

#  webview_pro_platform_interface: ^1.9.0
  webview_flutter_platform_interface:
    git:
      url: https://github.com/sribuu/flutter-plugins.git
      ref: dev-3.0.4
      path: packages/webview_flutter/webview_flutter/webview_flutter_platform_interface

#  webview_pro_wkwebview: ^2.8.0
  webview_flutter_wkwebview:
    git:
      url: https://github.com/sribuu/flutter-plugins.git
      ref: dev-3.0.4
      path: packages/webview_flutter/webview_flutter/webview_flutter_wkwebview

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.10.0
